[project]
name = "data-engineers-notebook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.4",
    "scikit-learn>=1.6.1",
    "xgboost>=3.0.0",
]
